# Generated by Django 3.0 on 2020-08-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=300)),
                ('product_date', models.DateField()),
                ('product_price', models.FloatField()),
                ('product_image', models.CharField(max_length=2083)),
            ],
        ),
    ]
